"""init tables

Revision ID: 770a7e6c33e9
Revises: 
Create Date: 2026-02-06 02:24:20.746344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770a7e6c33e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), server_default='momo', nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True, comment='Public avatar URL (CDN / signed URL if applicable)'),
    sa.Column('avatar_storage_key', sa.String(length=512), nullable=True, comment='Object storage key/path for avatar (e.g., s3 key)'),
    sa.Column('avatar_etag', sa.String(length=128), nullable=True, comment='Avatar version hash/etag for cache busting'),
    sa.Column('avatar_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last time avatar was updated'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='User timezone preference (IANA identifier)'),
    sa.Column('last_known_timezone', sa.String(length=50), nullable=True, comment='Last detected timezone from X-User-Timezone header'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('checkin_records',
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('local_date', sa.DateTime(), nullable=False),
    sa.Column('timezone_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_checkin_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkin_id', name=op.f('pk_checkin_records')),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_user_local_date_checkin')
    )
    op.create_index(op.f('ix_checkin_records_checkin_id'), 'checkin_records', ['checkin_id'], unique=False)
    op.create_index(op.f('ix_checkin_records_user_id'), 'checkin_records', ['user_id'], unique=False)
    op.create_table('checkin_reminders',
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('time_local', sa.String(length=5), nullable=False),
    sa.Column('frequency_type', sa.Enum('DAILY', 'EVERY_N_DAYS', name='frequencytype'), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_checkin_reminders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id', name=op.f('pk_checkin_reminders'))
    )
    op.create_index(op.f('ix_checkin_reminders_reminder_id'), 'checkin_reminders', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_checkin_reminders_user_id'), 'checkin_reminders', ['user_id'], unique=True)
    op.create_table('emergency_contacts',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_relationship', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_emergency_contacts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', name=op.f('pk_emergency_contacts'))
    )
    op.create_index(op.f('ix_emergency_contacts_contact_id'), 'emergency_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_email'), 'emergency_contacts', ['email'], unique=True)
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('journals',
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('occurred_at_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timezone_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_journals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('pk_journals'))
    )
    op.create_index(op.f('ix_journals_journal_id'), 'journals', ['journal_id'], unique=False)
    op.create_index(op.f('ix_journals_user_id'), 'journals', ['user_id'], unique=False)
    op.create_table('miss_checkin_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('threshold_days', sa.Integer(), nullable=False),
    sa.Column('message_template', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_miss_checkin_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_miss_checkin_rules'))
    )
    op.create_index(op.f('ix_miss_checkin_rules_rule_id'), 'miss_checkin_rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_miss_checkin_rules_user_id'), 'miss_checkin_rules', ['user_id'], unique=True)
    op.create_table('moods',
    sa.Column('mood_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('occurred_at_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timezone_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_moods_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mood_id', name=op.f('pk_moods')),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_user_local_date_mood')
    )
    op.create_index(op.f('ix_moods_mood_id'), 'moods', ['mood_id'], unique=False)
    op.create_index(op.f('ix_moods_user_id'), 'moods', ['user_id'], unique=False)
    op.create_table('pause_status',
    sa.Column('pause_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_pause_status_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pause_id', name=op.f('pk_pause_status'))
    )
    op.create_index(op.f('ix_pause_status_pause_id'), 'pause_status', ['pause_id'], unique=False)
    op.create_index(op.f('ix_pause_status_user_id'), 'pause_status', ['user_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of refresh token (not the token itself)'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expiration time (UTC)'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When token was revoked'),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True, comment='[FUTURE] Device identifier'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address when created'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent when created'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last time token was used'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('warm_message_groups',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.journal_id'], name=op.f('fk_warm_message_groups_journal_id_journals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_warm_message_groups')),
    sa.UniqueConstraint('group_id', 'journal_id', name='uq_warm_message_groups_group_id_journal_id')
    )
    op.create_index(op.f('ix_warm_message_groups_group_id'), 'warm_message_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_warm_message_groups_journal_id'), 'warm_message_groups', ['journal_id'], unique=True)
    op.create_table('warm_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['group_id', 'journal_id'], ['warm_message_groups.group_id', 'warm_message_groups.journal_id'], name=op.f('fk_warm_messages_group_id_warm_message_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.journal_id'], name=op.f('fk_warm_messages_journal_id_journals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_warm_messages'))
    )
    op.create_index(op.f('ix_warm_messages_group_id'), 'warm_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_warm_messages_journal_id'), 'warm_messages', ['journal_id'], unique=False)
    op.create_index(op.f('ix_warm_messages_message_id'), 'warm_messages', ['message_id'], unique=False)
    op.create_table('warm_msg_tags',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.Enum('EMPATHY', 'ENCOURAGEMENT', 'CALM', 'PROUD', 'GROUNDING', 'SUPPORT', 'HOPE', name='warm_tag'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['warm_messages.message_id'], name=op.f('fk_warm_msg_tags_message_id_warm_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'tag', name=op.f('pk_warm_msg_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warm_msg_tags')
    op.drop_index(op.f('ix_warm_messages_message_id'), table_name='warm_messages')
    op.drop_index(op.f('ix_warm_messages_journal_id'), table_name='warm_messages')
    op.drop_index(op.f('ix_warm_messages_group_id'), table_name='warm_messages')
    op.drop_table('warm_messages')
    op.drop_index(op.f('ix_warm_message_groups_journal_id'), table_name='warm_message_groups')
    op.drop_index(op.f('ix_warm_message_groups_group_id'), table_name='warm_message_groups')
    op.drop_table('warm_message_groups')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_pause_status_user_id'), table_name='pause_status')
    op.drop_index(op.f('ix_pause_status_pause_id'), table_name='pause_status')
    op.drop_table('pause_status')
    op.drop_index(op.f('ix_moods_user_id'), table_name='moods')
    op.drop_index(op.f('ix_moods_mood_id'), table_name='moods')
    op.drop_table('moods')
    op.drop_index(op.f('ix_miss_checkin_rules_user_id'), table_name='miss_checkin_rules')
    op.drop_index(op.f('ix_miss_checkin_rules_rule_id'), table_name='miss_checkin_rules')
    op.drop_table('miss_checkin_rules')
    op.drop_index(op.f('ix_journals_user_id'), table_name='journals')
    op.drop_index(op.f('ix_journals_journal_id'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_email'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_contact_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_checkin_reminders_user_id'), table_name='checkin_reminders')
    op.drop_index(op.f('ix_checkin_reminders_reminder_id'), table_name='checkin_reminders')
    op.drop_table('checkin_reminders')
    op.drop_index(op.f('ix_checkin_records_user_id'), table_name='checkin_records')
    op.drop_index(op.f('ix_checkin_records_checkin_id'), table_name='checkin_records')
    op.drop_table('checkin_records')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
